spec:
  name: evolution-todo
  region: nyc

  # Environment variables shared across all services
  envs:
    - key: NODE_ENV
      value: production
    - key: PYTHON_ENV
      value: production

  # Frontend Service - Next.js
  services:
    - name: frontend
      source_dir: frontend
      build_command: npm ci --legacy-peer-deps && npm run build
      run_command: npm start
      environment_slug: node-js
      instance_count: 1
      instance_size_slug: basic-xxs
      http_port: 3000
      routes:
        - path: /
      health_check:
        http_path: /
        initial_delay_seconds: 30
        period_seconds: 30
      envs:
        - key: NEXT_PUBLIC_API_URL
          scope: RUN_TIME
          value: ${backend.PUBLIC_URL}/api/v1
        - key: BETTER_AUTH_URL
          scope: RUN_TIME
          value: ${APP_URL}
        - key: BETTER_AUTH_SECRET
          scope: RUN_TIME
          type: SECRET
        - key: DATABASE_URL
          scope: RUN_TIME
          type: SECRET
        - key: BREVO_API_KEY
          scope: RUN_TIME
          type: SECRET
        - key: EMAIL_FROM_ADDRESS
          scope: RUN_TIME
          value: noreply@evolutionoftodo.com
        - key: EMAIL_FROM_NAME
          scope: RUN_TIME
          value: Evolution of Todo

    - name: backend
      source_dir: backend
      dockerfile_path: Dockerfile
      instance_count: 1
      instance_size_slug: basic-xxs
      http_port: 8000
      routes:
        - path: /api
          preserve_path_prefix: true
      health_check:
        http_path: /api/v1/health
        initial_delay_seconds: 30
        period_seconds: 30
      envs:
        - key: DATABASE_URL
          scope: RUN_TIME
          type: SECRET
        - key: BETTER_AUTH_SECRET
          scope: RUN_TIME
          type: SECRET
        - key: SECRET_KEY
          scope: RUN_TIME
          type: SECRET
        - key: BETTER_AUTH_URL
          scope: RUN_TIME
          value: ${APP_URL}
        - key: CORS_ORIGINS
          scope: RUN_TIME
          value: ${frontend.PUBLIC_URL}
        - key: API_PREFIX
          scope: RUN_TIME
          value: /api/v1
        - key: ENVIRONMENT
          scope: RUN_TIME
          value: production
        - key: BREVO_API_KEY
          scope: RUN_TIME
          type: SECRET
        - key: EMAIL_FROM_ADDRESS
          scope: RUN_TIME
          value: noreply@evolutionoftodo.com
        - key: EMAIL_FROM_NAME
          scope: RUN_TIME
          value: Evolution of Todo
        - key: GEMINI_API_KEY
          scope: RUN_TIME
          type: SECRET
        - key: OPENAI_API_KEY
          scope: RUN_TIME
          type: SECRET

  # Database - Neon PostgreSQL (external, managed separately)
  # Configure DATABASE_URL secret with your Neon connection string

  # Alerts and monitoring
  alerts:
    - rule: DEPLOYMENT_FAILED
    - rule: DOMAIN_FAILED
    - rule: CPU_UTILIZATION
      value: 85
      operator: GREATER_THAN
      window: FIVE_MINUTES
    - rule: MEM_UTILIZATION
      value: 85
      operator: GREATER_THAN
      window: FIVE_MINUTES
